on: pull_request

name: Changelog Reminder

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: peterjgrainger/action-changelog-reminder@v1.2.0
      with:
        changelog_regex: 'CHANGELOG.md'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
